windows: restrucutred buildagentprereq
CircleCI-Public/ansible pull request #164
Opened 2022-12-05 21:59 UTC by mrothstein74

- created new windows manifest
- create new roles/windows structure
- created new buildagent_prereq role
- create new windows playbook file at top level of repo

will keep old structure in place until the restructure is complete

2022-12-05 23:07 UTC, JalexChen requested changes

2022-12-05 23:07 UTC, JalexChen commented on roles/windows-executor/tasks/main.yml
> +  ansible.windows.win_reboot:
newline

2022-12-05 23:07 UTC, JalexChen commented on roles/windows/buildagent_prereq/tasks/main.yml
> +
fix newline

2022-12-06 01:02 UTC, mrothstein74 commented on roles/windows/buildagent_prereq/tasks/main.yml
> +
@JalexChen done

2022-12-06 01:38 UTC, JalexChen approved these changes

2023-01-10 18:33 UTC, merged